mpd_start() {
  if [ -x /usr/bin/mpd ]; then
    echo "Starting Music Player Daemon: /usr/bin/mpd... "
    /usr/bin/mpd /etc/mpd.conf &> /dev/null
    sleep 1 
  fi
}

mpd_stop() {
  echo "Stopping music player daemon..."
  /usr/bin/mpd --kill /etc/mpd.conf &> /dev/null
}

mpd_restart() {
  mpd_stop
  sleep 1
  mpd_start
}

case "$1" in
'start')
 mpd_start
  ;;
'stop')
  mpd_stop
  ;;
'restart')
 mpd_restart
  ;;
*)
  echo "usage $0 start|stop|restart"
esac

